name: CI

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: webiny/action-conventional-commits@v1.0.3
    - name: format code
      run: cargo test
